@file:Suppress("MagicNumber") // Color-token definitions: hex literals are the value, by design.

package com.mediplus.spapp.core.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 "Vibrant" tonal scheme seeded from the brand orange #EF5D22.
// Generated by @material/material-color-utilities (SchemeVibrant, contrast 0.0).
// Locked and guarded by SpAppThemeColorsTest — regenerate both together.
// Spec: docs/superpowers/specs/2026-07-27-material3-orange-theme-design.md

// --- Light: primary / secondary / tertiary ---
internal val Primary = Color(0xFFAA3700)
internal val OnPrimary = Color(0xFFFFFFFF)
internal val PrimaryContainer = Color(0xFFFFDBCF)
internal val OnPrimaryContainer = Color(0xFF822800)
internal val Secondary = Color(0xFF7E5537)
internal val OnSecondary = Color(0xFFFFFFFF)
internal val SecondaryContainer = Color(0xFFFFDCC5)
internal val OnSecondaryContainer = Color(0xFF633E22)
internal val Tertiary = Color(0xFF7E571D)
internal val OnTertiary = Color(0xFFFFFFFF)
internal val TertiaryContainer = Color(0xFFFFDDB5)
internal val OnTertiaryContainer = Color(0xFF633F05)

// --- Light: error ---
internal val Error = Color(0xFFBA1A1A)
internal val OnError = Color(0xFFFFFFFF)
internal val ErrorContainer = Color(0xFFFFDAD6)
internal val OnErrorContainer = Color(0xFF93000A)

// --- Light: neutral surfaces ---
internal val Background = Color(0xFFFFF8F6)
internal val OnBackground = Color(0xFF271813)
internal val Surface = Color(0xFFFFF8F6)
internal val OnSurface = Color(0xFF271813)
internal val SurfaceVariant = Color(0xFFFDDBD1)
internal val OnSurfaceVariant = Color(0xFF58423A)

// --- Light: utility ---
internal val Outline = Color(0xFF8C7169)
internal val OutlineVariant = Color(0xFFDFC0B6)
internal val Scrim = Color(0xFF000000)
internal val InverseSurface = Color(0xFF3D2D27)
internal val InverseOnSurface = Color(0xFFFFEDE8)
internal val InversePrimary = Color(0xFFFFB59C)

// --- Dark: primary / secondary / tertiary ---
internal val PrimaryDark = Color(0xFFFFB59C)
internal val OnPrimaryDark = Color(0xFF5C1A00)
internal val PrimaryContainerDark = Color(0xFF822800)
internal val OnPrimaryContainerDark = Color(0xFFFFDBCF)
internal val SecondaryDark = Color(0xFFF1BC96)
internal val OnSecondaryDark = Color(0xFF49290E)
internal val SecondaryContainerDark = Color(0xFF633E22)
internal val OnSecondaryContainerDark = Color(0xFFFFDCC5)
internal val TertiaryDark = Color(0xFFF1BD7A)
internal val OnTertiaryDark = Color(0xFF462B00)
internal val TertiaryContainerDark = Color(0xFF633F05)
internal val OnTertiaryContainerDark = Color(0xFFFFDDB5)

// --- Dark: error ---
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)

// --- Dark: neutral surfaces ---
internal val BackgroundDark = Color(0xFF1E100B)
internal val OnBackgroundDark = Color(0xFFF9DDD4)
internal val SurfaceDark = Color(0xFF1E100B)
internal val OnSurfaceDark = Color(0xFFF9DDD4)
internal val SurfaceVariantDark = Color(0xFF58423A)
internal val OnSurfaceVariantDark = Color(0xFFDFC0B6)

// --- Dark: utility ---
internal val OutlineDark = Color(0xFFA78B81)
internal val OutlineVariantDark = Color(0xFF58423A)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFF9DDD4)
internal val InverseOnSurfaceDark = Color(0xFF3D2D27)
internal val InversePrimaryDark = Color(0xFFAA3700)

// --- Status: success (outside Material's scheme, so not generated with the palette above) ---
// Hand-picked greens: the brand primary is orange, too close to error red to mark a pass.
// Guarded by SpAppThemeColorsTest (green-dominant, ≥ 3:1 against surface; onSuccess ≥ 4.5:1 on it).
internal val Success = Color(0xFF2E7D32)
internal val OnSuccess = Color(0xFFFFFFFF)
internal val SuccessDark = Color(0xFF81C784)
internal val OnSuccessDark = Color(0xFF00390A)

// --- Status: warning (hand-picked like success) ---
// Amber rather than orange, so it cannot be read as the brand primary or as error red.
// Guarded by SpAppThemeColorsTest (amber, apart from success and error, ≥ 3:1 against surface).
internal val Warning = Color(0xFF946200)
internal val WarningDark = Color(0xFFFFCA28)
